### ISSUE TITLE
Property Transfer failed

### ISSUE THREAD

**Issue by spullagura** [byte-shifter-ltd/soapui-gradle-plugin#11]
Hi,
I used this plugin to run my soap ui tests. I got the following error:
 [com.lv.plugins.soapui.tasks.MySoapUITestCaseRunner] PropertyTransfer failed, exporting to ...

I could run my tests successfully in Ready! API 1.4.0.

Could you please provide your input on this?

Below is my build.gradle:

// Apply the java plugin to add support for Java
apply plugin: 'java'
apply plugin: 'com.lv.soapui'

task wrapper(type: Wrapper) {
    gradleVersion = '2.3'
}

// In this section you declare where to find the dependencies of your build script
buildscript {
    repositories {
			mavenLocal()
			//This repository contains the missing dependencies 
			maven {
				url "http://repo1.maven.org/maven2/"
			}
			maven {
				url "http://www.soapui.org/repository/maven2/"
			}			
	}
	dependencies {        
        classpath 'com.lv.plugins:soapui-gradle-plugin:0.1'	
    }	
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
		
}

soapui {
	   test {
        projectFile = 'Project-name-soapui-project.xml'
        printReport = true
        junitReport = true
	testSuite = 'TestSuite 1'
    }
}

Thanks!

**Comment by willis7** [comment]
Hi, this plugin has been through a few iterations and could do with an update to the Gradle portal. I will make the change and update here.

**Comment by willis7** [comment]
The plugin is now hosted in the Gradle Plugin Portal.  See instructions:

[Gradle Plugin Portal](https://plugins.gradle.org/plugin/io.byteshifter.soapui)

**Comment by spullagura** [comment]
Thank you!
