### ISSUE TITLE
Typo in TestTask.groovy

### ISSUE THREAD

**Issue by 80586** [byte-shifter-ltd/soapui-gradle-plugin#12]
Hello,

There is a typo in the soapui-gradle-plugin. In src/main/groovy/io/byteshifter/plugins/soapui/tasks/TestTask.groovy, line 219, projectProperties() should be getProjectProperties().

This causes the setting of the projectProperties key in the soapui -> test closure to throw a NullPointerException.

The fork at [https://github.com/creising/soapui-gradle-plugin] is also affected.

**Comment by willis7** [comment]
Hi @80586 ,

Thanks for highlighting this. I will look to fix this soon. If in the meantime you would like to make a pull request I will be happy to merge that in.

**Comment by willis7** [comment]
This should fix your immediate problem, but this has highlighted concerns elsewhere in the plugin.
