### ISSUE TITLE
Assertions fail but pass in the SoapUI application

### ISSUE THREAD

**Issue by g1ps** [byte-shifter-ltd/soapui-gradle-plugin#15]
Hi,

I'm trying to run existing tests using Gradle and your plugin. We have a custom namespace and a bunch of tests that run regularly and pass. When I try to run them through the plugin, the test is able to authenticate with the service and retrieve a valid response but the assertions fail. The assertions pass using SoapUI 4.5.2 and 5.3.0. The plugin uses 5.0.1. I haven't been able to test whether that's a factor.

Here's an extract from the response
```
  <sample xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="<custom ns>">
     <id>2</id>
     <material_alias>Cold-Cold</material_alias>
     <material_id>23</material_id>
     <name>CT-000000023-0</name>
     <original_experiment_id>1</original_experiment_id>
     <priority>3</priority>
     <hazards>
        ...
```

and here are two of the assertions
```
            <con:assertion type="XPath Match" name="Sample exists">
              <con:configuration>
                <path>declare namespace ns1='<custom ns>';
exists(/ns1:sample)</path>
                <content>true</content>
                <allowWildcards>false</allowWildcards>
                <ignoreNamspaceDifferences>false</ignoreNamspaceDifferences>
                <ignoreComments>false</ignoreComments>
              </con:configuration>
            </con:assertion>
            <con:assertion type="XPath Match" name="Assert id">
              <con:configuration>
                <path>declare namespace ns1='<custom ns>;
/ns1:sample/ns1:id</path>
                <content>2</content>
                <allowWildcards>false</allowWildcards>
                <ignoreNamspaceDifferences>false</ignoreNamspaceDifferences>
                <ignoreComments>false</ignoreComments>
              </con:configuration>
            </con:assertion>
```
and here are the results
```
  ----------------- Messages ------------------------------
  [Sample exists] XPathContains assertion failed for path [declare namespace ns1='<custom ns>';
exists(/ns1:sample)] : RuntimeException: Trying XBeans path engine... Trying XQRL..
. Trying XDK... Trying delegated path engine... FAILED on declare namespace ns1='<custom ns>';
exists(/ns1:sample)
  [Assert id] XPathContains assertion failed for path [declare namespace ns1='<custom ns>';
/ns1:sample/ns1:id] : RuntimeException: Trying XBeans path engine... Trying XQRL...
 Trying XDK... Trying delegated path engine... FAILED on declare namespace ns1='<custom ns>';
/ns1:sample/ns1:id
```
Everything I've read says that the first slash before ```ns1``` should be doubled. I've tried that both in Gradle and SoapUI and it hasn't changed things. I've also tried all sorts of variations, playing with namespaces, adding new assertions, etc. I can add new ones that pass in the app. I've been unable to add a single assertion that works in Gradle. I haven't been able to find where the plugin stores it's soapui jar to see if updating it would help.

I can't see any reason why these assertions should fail and, given that they pass in two versions of SoapUI, it does look like there's a bug somewhere. This is a blocking issue for me so any help will be appreciated.

Thanks.

**Comment by willis7** [comment]
Hi @g1ps, thanks for your interest in this plugin. Unfortunately, I'm no longer in a position to support this plugin. I will be happy to take PR's and would welcome any contributions

**Comment by g1ps** [comment]
Hi. Yes, I know. I'm hoping that someone else might be able to help.

**Comment by daggerok** [comment]
fixed here: #28 
@g1ps 
as soon @willis7 will publish 5.3.0 version it would use tetrunner of SoapUI 5.3.0

**Comment by g1ps** [comment]
OK, thanks. I will retry with the new version when time permits. It may take a little while.

**Comment by daggerok** [comment]
@g1ps plugin versions 5.3.0 and 5.3.1-RC are available in gradle portal.

Hope it can help.

---
Regards, Max

**Comment by g1ps** [comment]
No change, I'm afraid, @daggerok . It fails identically. I also discovered your soapui-runner and had high hopes of success but, no. It has stopped an auth error for me, which I appreciate, but I can't for the life of me work out what's going on with these XPathContains assertions. Your plug in throws them just the same. The tests work from SOAP UI itself. None of us here can work this out. I assume that there's something wrong or different about how I'm configuraing the plug-ins or running the tests but this is just killing us. If you can throw any light on the problem I'd be delighted.

Cheers.

**Comment by daggerok** [comment]
is it something special in yor ext folder? maybe you are using some library from there, but on gradle plugin runtime it couldn't be found in classpath?
for soapui-runner config should be enough just put it in extDir closure like described [here
](https://daggerok.github.io/soapui-runner/#extDir)
---
Regards

**Comment by g1ps** [comment]
> @g1ps, can you verify if there are something special in your local SoapUI ext folder (different from default soapui installation)?

Good thought but there isn't. It's empty.

> btw, as far as I remember XPath query alias should start from doubled slashes

Yeah, thanks for the reminder. That one beats me. Our tests run like this. I was also having the soapuios issue but resolved that with the help of your FAQ. I've now tried reducing it to a single test, changed those slashes, and played around in all sorts of ways with the namespace but nothing prevents it failing.

The API returns
```
  <external_link_types xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="
http://<custom>/api/1.0">
     <external_link_type>
      ...
     </external_link_type>
  </external_link_types>
```
and the test fails with
```
  [External Link types exists] XPathContains assertion failed for path [declare na
mespace ns1='http://<custom>/api/1.0/';exists(//ns
1:external_link_types)] : RuntimeException: Trying XBeans path engine... Trying XQ
RL... Trying XDK... Trying delegated path engine... FAILED on declare namespace ns
1='http://<custom>/api/1.0/';exists(//ns1:external
_link_types)
```
The path is configured thus:
```
<path>declare namespace ns1='http://<custom>/api/1.0/';exists(//ns1:external_link_types)</path>
```
All 3 soapui plugins fail it this way so it must be something in the tests but I just don't know what.

**Comment by daggerok** [comment]
heh :)
sorry, but I don't know how I can help you

lastly, just try use [testrunner.sh (or testrunner.bat if you are on windows)](https://www.soapui.org/test-automation/running-functional-tests.html) from local SoapUI installation...

actually, right now I'm interesting if your test project in this case will also fails

/br max

**Comment by g1ps** [comment]
Hi there,

I had a quick try but it fails to load classes and I don't have time to find out why. What I can say is that the same test suites run daily on our legacy, Ant-driven system without issues, even with the single slash in the call to exists(). My current work-around is to run that same Ant build from Gradle and that works, too. It's only the Gradle plug-ins that are causing trouble.

Cheers.
