### ISSUE TITLE
Missing Documentation for Configuration of Client Certificate Based Authentication 

### ISSUE THREAD

**Issue by wyjacobs** [byte-shifter-ltd/soapui-gradle-plugin#31]
Hi, I'am trying to configure SSL Client Certificate Based Authentication. When using SoapUI I can do this like described in this link: https://blogs.sap.com/2011/01/06/soap-ui-tool-soap-https-client-authentication/
And that works also for me.

Unfortunately, when I'm trying to configure this via gradle it doesn't work. Specifically, it does not send the client certificate to server.

My configuration, which I tryed till now, looks like this:

soapUITest.projectProperties = ["clientAuthentication=true", "sslKeystore=${projectDir}/src/test/resources/mobileV2-test-certificates/mobileTest/mobileTest.p12", "sslKeystorePassword=********"]

Did someone try to set a client certificate for soap requests with this plugin? Is my configuration wrong?

Ragards,
Giacomo

**Comment by daggerok** [comment]
Hi,

I can try investigate if will provide more information

better is provide test project beckend you sending request from soap ui, and worked soapui test project itself within certificates

**Comment by wyjacobs** [comment]
Hi @daggerok 

Thank you a lot for answering that quick. Currently, I have not a small test backend which I could provide you on the fly. 

I think a big help would be, if I knew how to name the properties for the keystore setup. Apparently, "sslKeyStore" and "sslKeystorePassword" don't take effect.

In the Java SoapUI version, the only three things I have to provide are as follows: 
![grafik](https://user-images.githubusercontent.com/6442237/31887810-f8f0abfc-b7f9-11e7-984a-3de4b1195da5.png)

**Comment by daggerok** [comment]
Sorry, but I don't have a time to setup such backend and play around that

If you already have sopui project and just wana run it via gradle, I can propose you try [that gradle soapui test runner](https://daggerok.github.io/soapui-runner/). Readme of github project contains [simple example](https://github.com/daggerok/soapui-runner) of it configuration

---
Regards,
Maksim

**Comment by wyjacobs** [comment]
Hi Maksim

Thank you for your hint. In the coming days I will try out this soapui test.

Regards,
Giacomo

**Comment by daggerok** [comment]
Closing this issue anyway...
