### ISSUE TITLE
How to add jdbc driver to Soapui using soapui-gradle-plugin?

### ISSUE THREAD

**Issue by tann200** [byte-shifter-ltd/soapui-gradle-plugin#32]
When using SoapUI, its possible to use postgresql driver in path=>SmartBear/SoapUI-5.4.0/bin/ext
But how and where to define the postrgresql driver for soapui-gradle-plugin?
Should it be done in soapui tests or should it be added to build.gradle as a dependency?

**Comment by daggerok** [comment]
something like this might works:

```groovy
configurations {
    driver
}

dependencies {
    driver 'org.postgresql:postgresql:9.4-1201-jdbc41'
}

URLClassLoader loader = GroovyObject.class.classLoader
configurations.driver.each { File file ->
    loader.addURL(file.toURL())
}
```

**Comment by daggerok** [comment]
I believe, I can close this issue
