### ISSUE TITLE
Test step properties question

### ISSUE THREAD

**Issue by blui** [byte-shifter-ltd/soapui-gradle-plugin#36]
Hello! I'd like to ask if the plugin allows users to specify specific properties to use for different test steps. Say, for example, We have test step A and test step B.

I want the plugin to run both A and B in succession, but use a header value X for test step A and a header value Y for test step B.

If this feature isn't yet supported, I am wondering if there will be any plans to add the support.

Thank you!

**Comment by daggerok** [comment]
Hello, try this gradle [soapui-runner](https://daggerok.github.io/soapui-runner/#adding-new-and-override-generic-parent-properties) as far as I remember it should support what you need
