### ISSUE TITLE
Dangling JVM process after integration test

### ISSUE THREAD

**Issue by willis7** [byte-shifter-ltd/soapui-gradle-plugin#9]
When the integration tests are run I can see Java processes are left hanging using `ps -fe | grep java`. These processes need to be cleaned after execution.

**Comment by willis7** [comment]
This seems to relate to Nebula test:
https://github.com/nebula-plugins/nebula-test/issues/55

**Comment by daggerok** [comment]
have you tried `bash gradlew --stop`?

**Comment by willis7** [comment]
Sure thing
